### ISSUE TITLE
Could you add `example` to the topics of this repository?

### ISSUE THREAD

**Issue by iesahin** [iterative/example-mlem-frozen-0.1.7#1]
It will make searching the repository easier. Thank you. 

@aguschin

**Comment by aguschin** [comment]
Hi @iesahin! AFAIK, this is @Suor's temporary fork for Studio BE development purposes. It shouldn't be used as an example for users.

**Comment by iesahin** [comment]
Then, I think putting a `temporary` label may also be appropriate. We're trying to have a clear picture of the 150 repositories we have :) @Suor

**Comment by Suor** [comment]
It's not temporary. It's frozen, I will add something to description.

**Comment by Suor** [comment]
Updated the description.

**Comment by iesahin** [comment]
Thank you @Suor.
